coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        # If true PRs will always pass and reports are just for information
        informational: true

# post comment on PR
comment: false

# enable codecov to report to GitHub status checks
github_checks:
  annotations: false

# ignore files
ignore:
  - ".github/"
  - "_build_tools/"
  - "_uea_experiments/"
  - "docs/"
  - "examples/"
  - "results/"
  - "tsml_eval/_wip/"
