[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tsml-eval"
version = "0.0.2"
description = "A package for benchmarking time series machine learning tools."
authors = [
    {name = "Matthew Middlehurst", email = "m.middlehurst@uea.ac.uk"},
    {name = "Tony Bagnall", email = "ajb@uea.ac.uk"},
]
readme = "README.md"
requires-python = ">=3.8,<3.11"
keywords = [
    "data-science",
    "machine-learning",
    "time-series",
    "evaluation",
    "benchmarking",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
dependencies = [
    "sktime>=0.15.0,<=0.16.0",
    "scikit-learn",
    "convst",
    "wildboar",
    "stumpy",
    "xgboost",
    "networkx",
    "requests",
    "gpustat",
    "scikit-fda",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
    "pytest-randomly",
    "pytest-timeout",
    "pytest-xdist",
    "pytest-cov",
]
docs = [
    "sphinx",
    "sphinx-design",
    "sphinx-gallery",
    "nbsphinx",
    "numpydoc",
    "jupyter",
    "furo",
]
deep_learning = [
    "tensorflow",
    "tensorflow-probability",
    "torch>=1.13.1",
]

[project.urls]
homepage = "https://www.timeseriesclassification.com/"
repository = "https://github.com/time-series-machine-learning/tsml-eval/"

[project.license]
file = "LICENSE"

[tool.setuptools.packages.find]
include = ["tsml_eval"]

[tool.check-manifest]
ignore = [
    "_uea_experiments/**",
    "examples/**",
    "results/**",
    "docs/**",
    "requirements.txt",
    "*.yaml",
    "*.yml",
    ".coveragerc",
]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = [
    "tsml_eval/_wip/*",
    "examples/_wip/*"
]
per-file-ignores = [
    "tsml_eval/experiments/classification_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_classification_experiments.py:T201",
    "tsml_eval/experiments/regression_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_regression_experiments.py:T201",
    "tsml_eval/experiments/clustering_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_clustering_experiments.py:T201",
    "tsml_eval/experiments/distance_clustering_experiments.py:E402,T201",
]

[tool.nbqa.exclude]
black = "^docs/examples/|^examples/_wip/"
flake8 = "^docs/examples/|^examples/_wip/"
isort = "^docs/examples/|^examples/_wip/"

[tool.pytest.ini_options]
addopts = '''
    --ignore tsml_eval/_wip
    --durations 10
    --timeout 600
    --showlocals
    --doctest-modules
    --numprocesses auto
    --cov tsml_eval
    --cov-report xml
'''
