[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tsml-eval"
version = "0.0.1"
description = "A package for benchmarking time series machine learning tools."
authors = [
    {name = "Matthew Middlehurst", email = "m.middlehurst@uea.ac.uk"},
    {name = "Tony Bagnall", email = "ajb@uea.ac.uk"},
]
readme = "README.md"
requires-python = ">=3.7,<3.11"
keywords = [
    "data-science",
    "machine-learning",
    "data-mining",
    "time-series",
    "classification",
    "regression",
    "clustering",
]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
]
dependencies = [
    "sktime>=0.14.0",
    "convst",
    "wildboar",
    "stumpy",
    "networkx",
    "requests",
    "torch",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
    "pytest",
]

docs = [
    "sphinx",
    "sphinx-design",
    "sphinx-gallery",
    "numpydoc",
    "nbsphinx",
    "furo",
]

[project.urls]
homepage = "https://www.timeseriesclassification.com/"
repository = "https://github.com/time-series-machine-learning/tsml-estimator-evaluation/"

[project.license]
file = "LICENSE"

[tool.setuptools.packages.find]
include = ["tsml_eval"]

[tool.check-manifest]
ignore = [
    "ada_uea_experiments/**",
    "notebooks/**",
    "results/**",
    "docs/**",
    "requirements.txt",
    "*.yaml",
]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203"]
exclude = ["tsml_eval/_wip/*"]
per-file-ignores = [
    "tsml_eval/experiments/classification_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_classification_experiments.py:T201",
    "tsml_eval/experiments/regression_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_regression_experiments.py:T201",
    "tsml_eval/experiments/clustering_experiments.py:E402,T201",
    "tsml_eval/experiments/threaded_clustering_experiments.py:T201",
    "tsml_eval/experiments/distance_clustering_experiments.py:E402,T201",
]
