name: examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "examples/**"
      - "tsml_eval/**"
      - ".github/workflows/**"
      - "pyproject.toml"
  schedule:
    # every day at 1:30 AM UTC
    - cron: "30 1 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-notebook-examples:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 30
          max_attempts: 3
          command: python -m pip install .[dev,all_extras,unstable_extras,binder]

      - name: Run example notebooks
        run: build_tools/run_examples.sh
        shell: bash
