name: examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "examples/**"
      - "tsml_eval/**"
      - ".github/workflows/**"
      - "pyproject.toml"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  run-notebook-examples:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install aeon and dependencies
        run: python -m pip install .[dev,all_extras,unstable_extras,binder]

      - name: Run example notebooks
        run: _build_tools/run_examples.sh
        shell: bash
